version: '2'
services:
    angularcrud-app:
        image: angularcrud
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularcrud-mysql:3306/angularcrud?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularcrud-mysql:
        extends:
            file: mysql.yml
            service: angularcrud-mysql
